# -*- coding: utf-8 -*-
"""
Pacote de Domínio — Agente Sniper
Camada de lógica de negócio pura, modelos de dados e regras canônicas sem dependências de infraestrutura.
"""

from domain.models import Fonte, PriceItem
from domain.normalizer import (
    normalizar,
    remover_acentos,
    termo,
    truncar,
    parse_data,
    parse_money,
    normalizar_quantidade,
    nome_produto_normalizado,
    tokens_produto,
    score_clamp,
)
from domain.identity import (
    sha1,
    url_normalizada,
    dominio,
    data_na_url,
    data_publicacao,
    cidade_ok,
    estado_ok,
    identidade_conflitante,
)
from domain.matching import similaridade_produto
from domain.events import (
    EVENT_RULES,
    RISK_KINDS,
    OPPORTUNITY_KINDS,
    CONFIANCA_CONFIRMADO,
    CONFIANCA_PROVAVEL,
    CONFIANCA_SINAL,
    CONFIANCA_INSUFICIENTE,
    identificar_independencia_fontes,
    possui_fonte_oficial,
    classificar_confianca_evento,
    enriquecer_evento_com_confianca,
    recencia_score,
    qualidade_fonte,
    evento_titulo_estavel,
    canonical_event_key,
    _primary_event_kind,
    eventos_sao_mesmo_fato,
    criar_eventos,
)
from domain.deltas import (
    calcular_delta_fontes,
    calcular_delta_eventos,
    ESTADO_EVENTO_NOVO,
    ESTADO_EVENTO_RECORRENTE,
    ESTADO_EVENTO_INATIVO_EXPIRADO,
)
from domain.pricing import (
    detectar_mudancas_preco,
    calcular_serie_temporal_precos,
)
from domain.scoring import (
    medir_dimensoes,
    score_ambiente_competitivo,
    score_pressao_competitiva,
    score_vulnerabilidade_empresa,
    classificar_sinal,
    acao_evento,
    gerar_sinais_deterministicos,
    score_momentum,
)
from domain.decision import (
    inteligencia_deterministica,
    validar_ids_sinais,
    validar_pacote,
)

__all__ = [
    "Fonte",
    "PriceItem",
    "normalizar",
    "remover_acentos",
    "termo",
    "truncar",
    "parse_data",
    "parse_money",
    "normalizar_quantidade",
    "nome_produto_normalizado",
    "tokens_produto",
    "score_clamp",
    "sha1",
    "url_normalizada",
    "dominio",
    "data_na_url",
    "data_publicacao",
    "cidade_ok",
    "estado_ok",
    "identidade_conflitante",
    "similaridade_produto",
    "EVENT_RULES",
    "RISK_KINDS",
    "OPPORTUNITY_KINDS",
    "CONFIANCA_CONFIRMADO",
    "CONFIANCA_PROVAVEL",
    "CONFIANCA_SINAL",
    "CONFIANCA_INSUFICIENTE",
    "identificar_independencia_fontes",
    "possui_fonte_oficial",
    "classificar_confianca_evento",
    "enriquecer_evento_com_confianca",
    "recencia_score",
    "qualidade_fonte",
    "evento_titulo_estavel",
    "canonical_event_key",
    "_primary_event_kind",
    "eventos_sao_mesmo_fato",
    "criar_eventos",
    "calcular_delta_fontes",
    "calcular_delta_eventos",
    "ESTADO_EVENTO_NOVO",
    "ESTADO_EVENTO_RECORRENTE",
    "ESTADO_EVENTO_INATIVO_EXPIRADO",
    "detectar_mudancas_preco",
    "calcular_serie_temporal_precos",
    "medir_dimensoes",
    "score_ambiente_competitivo",
    "score_pressao_competitiva",
    "score_vulnerabilidade_empresa",
    "classificar_sinal",
    "acao_evento",
    "gerar_sinais_deterministicos",
    "score_momentum",
    "inteligencia_deterministica",
    "validar_ids_sinais",
    "validar_pacote",
]
